const std = @import("std");
const ast = @import("ast.zig");
const Io = std.Io;

/// Emit a C-ABI sketch for a Cell module.
pub const Generator = struct {
    allocator: std.mem.Allocator,
    writer: *Io.Writer,

    pub fn init(allocator: std.mem.Allocator, writer: *Io.Writer) Generator {
        return .{
            .allocator = allocator,
            .writer = writer,
        };
    }

    pub fn emitModule(self: *Generator, module: *const ast.Module) !void {
        const out = self.writer;
        try out.writeAll("// Generated by cell (MVP IR sketch)\n");
        try out.writeAll("// Target ABI: C (callable from Zig / Swift / C++)\n");
        try out.print("// source: {s}\n\n", .{module.path});
        try out.writeAll("#include <stdint.h>\n#include <stdbool.h>\n\n");

        for (module.items) |item| {
            switch (item) {
                .fn_def => |f| try emitFn(out, f),
                .struct_def => |s| try emitStruct(out, s),
                .enum_def => |e| try emitEnum(out, e),
                .use_decl => |u| try out.print("// use {s}\n", .{u}),
            }
        }
    }

    fn emitFn(out: *Io.Writer, f: ast.FnDef) !void {
        if (f.is_public) try out.writeAll("// export\n");
        const ret = if (f.return_type) |t| cType(&t) else "void";
        try out.print("{s} cell_{s}(", .{ ret, f.name });
        for (f.params, 0..) |p, i| {
            if (i > 0) try out.writeAll(", ");
            try out.print("{s} /*{s}*/ {s}", .{ cType(&p.ty), @tagName(p.ownership), p.name });
        }
        try out.writeAll(")");
        if (f.body == null) {
            try out.writeAll(";\n\n");
            return;
        }
        try out.writeAll(" {\n");
        if (f.body) |body| {
            for (body) |stmt| try emitStmt(out, stmt, 1);
        }
        try out.writeAll("}\n\n");
    }

    fn emitStmt(out: *Io.Writer, stmt: ast.Stmt, indent: usize) !void {
        try writeIndent(out, indent);
        switch (stmt) {
            .let => |l| {
                const ty = if (l.ty) |t| cType(&t) else "int64_t";
                try out.print("{s} {s}", .{ ty, l.name });
                if (l.value) |v| {
                    try out.writeAll(" = ");
                    try emitExpr(out, v);
                }
                try out.writeAll(";\n");
            },
            .return_stmt => |opt| {
                try out.writeAll("return");
                if (opt) |v| {
                    try out.writeAll(" ");
                    try emitExpr(out, v);
                }
                try out.writeAll(";\n");
            },
            .expr => |e| {
                try emitExpr(out, e);
                try out.writeAll(";\n");
            },
            .assign => |a| {
                try out.print("{s} = ", .{a.name});
                try emitExpr(out, a.value);
                try out.writeAll(";\n");
            },
        }
    }

    fn emitExpr(out: *Io.Writer, expr: ast.Expr) !void {
        switch (expr) {
            .ident => |n| try out.writeAll(n),
            .int => |v| try out.print("{d}", .{v}),
            .float => |v| try out.print("{d}", .{v}),
            .string => |s| try out.print("\"{s}\"", .{s}),
            .bool => |b| try out.writeAll(if (b) "true" else "false"),
            .call => |c| {
                try emitExpr(out, c.callee.*);
                try out.writeAll("(");
                for (c.args, 0..) |a, i| {
                    if (i > 0) try out.writeAll(", ");
                    try emitExpr(out, a);
                }
                try out.writeAll(")");
            },
            .binary => |b| {
                try out.writeAll("(");
                try emitExpr(out, b.left.*);
                try out.writeAll(switch (b.op) {
                    .add => " + ",
                    .sub => " - ",
                    .mul => " * ",
                    .div => " / ",
                    .eq => " == ",
                    .ne => " != ",
                    .lt => " < ",
                    .le => " <= ",
                    .gt => " > ",
                    .ge => " >= ",
                    .and_op => " && ",
                    .or_op => " || ",
                });
                try emitExpr(out, b.right.*);
                try out.writeAll(")");
            },
            .unary => |u| {
                try out.writeAll(switch (u.op) {
                    .neg => "-",
                    .not => "!",
                    .ref_shared => "&",
                    .ref_exclusive => "&",
                });
                try emitExpr(out, u.operand.*);
            },
            .block => try out.writeAll("/*block*/"),
            .if_expr => try out.writeAll("/*if*/"),
            .match_expr => try out.writeAll("/*match*/"),
        }
    }

    fn emitStruct(out: *Io.Writer, s: ast.StructDef) !void {
        try out.print("typedef struct cell_{s} {{\n", .{s.name});
        for (s.fields) |f| {
            try out.print("  {s} {s}; // {s}\n", .{ cType(&f.ty), f.name, @tagName(f.ownership) });
        }
        try out.print("}} cell_{s};\n\n", .{s.name});
    }

    fn emitEnum(out: *Io.Writer, e: ast.EnumDef) !void {
        try out.print("typedef enum cell_{s} {{\n", .{e.name});
        for (e.variants) |v| {
            try out.print("  cell_{s}_{s},\n", .{ e.name, v });
        }
        try out.print("}} cell_{s};\n\n", .{e.name});
    }

    fn cType(ty: *const ast.TypeExpr) []const u8 {
        return switch (ty.*) {
            .name => |n| mapPrimitive(n),
            .optional => "void*", // nullable
            .list => "void*",
            .result => "cell_result_t",
            .ref => "void*",
            .unit => "void",
        };
    }

    fn mapPrimitive(name: []const u8) []const u8 {
        if (std.mem.eql(u8, name, "Int") or std.mem.eql(u8, name, "Int64")) return "int64_t";
        if (std.mem.eql(u8, name, "Int32")) return "int32_t";
        if (std.mem.eql(u8, name, "UInt") or std.mem.eql(u8, name, "UInt64")) return "uint64_t";
        if (std.mem.eql(u8, name, "Float") or std.mem.eql(u8, name, "Float64")) return "double";
        if (std.mem.eql(u8, name, "Float32")) return "float";
        if (std.mem.eql(u8, name, "Bool")) return "bool";
        if (std.mem.eql(u8, name, "String")) return "const char*";
        if (std.mem.eql(u8, name, "Byte")) return "uint8_t";
        return "void*";
    }

    fn writeIndent(out: *Io.Writer, n: usize) !void {
        var i: usize = 0;
        while (i < n) : (i += 1) try out.writeAll("  ");
    }
};
