//! Module emission: the generator's entry points, struct and optional instance
//! ordering, enums, prototypes, and function signatures.
//! Part of the C backend; the rules and their rationale are in the module header of `../codegen.zig`.

const std = @import("std");
const ast = @import("../ast.zig");
const borrowck = @import("../borrowck.zig");
const Io = std.Io;
const Alloc = std.mem.Allocator.Error;
const cg_helpers = @import("helpers.zig");
const cg_model = @import("model.zig");
const cg_root = @import("../codegen.zig");
const Generator = cg_root.Generator;
const EmitError = cg_root.EmitError;
const CType = cg_model.CType;
const StructEmitState = cg_model.StructEmitState;
const OptionalInst = cg_model.OptionalInst;
const intrinsicSymbol = cg_helpers.intrinsicSymbol;
const endsInReturn = cg_helpers.endsInReturn;
const blockExit = cg_helpers.blockExit;
const stmtsUse = cg_helpers.stmtsUse;

pub fn init(allocator: std.mem.Allocator, writer: *Io.Writer) Generator {
    return .{
        .allocator = allocator,
        .writer = writer,
    };
}

// ── module ──────────────────────────────────────────────────────────

pub fn emitModule(self: *Generator, module: *const ast.Module) EmitError!void {
    var arena_state = std.heap.ArenaAllocator.init(self.allocator);
    defer arena_state.deinit();

    self.arena = arena_state.allocator();
    self.module = module;
    self.locals = .empty;
    self.temp_counter = 0;
    self.next_binding_id = 0;

    // One borrow-check pass over the whole module, up front, so its
    // binding ids never reset mid-module -- see the module doc
    // comment's id-numbering agreement. `checker.hasErrors()` is
    // deliberately not consulted: this backend has never validated its
    // input (there is no type checker feeding it either, per the
    // module doc comment above), and codegen still emits best-effort C
    // for a module borrowck rejects, same as before this task. Only
    // `wasMoved` is read from it.
    var checker = borrowck.Checker.init(self.allocator, module.path, null);
    defer checker.deinit();
    try checker.checkModule(module);
    self.checker = &checker;
    defer self.checker = null;

    const out = self.writer;
    try out.writeAll("// Generated by cell.\n");
    try out.writeAll("// Target ABI: runtime/cell_rt.h (callable from Zig / Swift / C++).\n");
    try out.print("// source: {s}\n\n", .{module.path});
    try out.writeAll("#include \"cell_rt.h\"\n\n");

    for (module.items) |item| {
        if (item.kind == .use_decl) try out.print("// use {s}\n", .{item.kind.use_decl});
    }

    // Enums first, unconditionally: an enum is a `typedef int32_t` with no
    // dependencies, and a struct field may name an enum while an enum can
    // never name a struct, so hoisting them cannot introduce an ordering
    // problem and removes one.
    for (module.items) |item| {
        if (item.kind == .enum_def) try self.emitEnum(item.kind.enum_def);
    }
    try self.emitStructsInDependencyOrder(module);

    try self.emitOptionalInstances();
    try self.emitDropGlue(module);
    try self.emitResultDropGlue(module);

    var wrote_prototype = false;
    for (module.items) |item| {
        if (item.kind != .fn_def) continue;
        try self.emitPrototype(item.kind.fn_def);
        wrote_prototype = true;
    }
    if (wrote_prototype) try out.writeAll("\n");

    for (module.items) |item| {
        if (item.kind != .fn_def) continue;
        if (item.kind.fn_def.body == null) continue;
        try self.emitFn(item.kind.fn_def);
    }

    try self.emitEntryPoint();
}

/// Struct typedefs in dependency order rather than source order.
///
/// `struct A { owned b: B }` written above `struct B` used to emit
/// `cell_A` first, and `cc` refused the module with
/// `unknown type name 'cell_B'` while `cell check` accepted it -- a
/// front end that passes and a back end that cannot be compiled.
/// A field naming another struct needs that struct's typedef already
/// emitted whether the field is a value (`cell_B b;`) or a `ref`
/// (`cell_B *b;`), so the edge is taken from any `.name` appearing
/// anywhere in the field's type expression. That is deliberately
/// conservative: `[B]` lowers to the opaque `cell_slice_t` and needs no
/// edge, but adding one only constrains the order further, and being
/// wrong in that direction costs nothing while missing an edge emits
/// C that does not compile.
///
/// Depth-first post-order, source order among independent structs so the
/// common case keeps emitting exactly as it did.
///
/// On a cycle the back edge is dropped and both structs still emit, in
/// post-order: `struct A { owned b: B }` with `struct B { owned a: A }`
/// emits B then A, so a cycle IS reordered. That is worth stating
/// precisely because the first version of this comment claimed the cycle
/// was "left in source order", which is not what the code does -- the
/// `visiting` arm returns rather than unwinding, so A's recursion into B
/// completes and B is emitted first. Nothing is lost by it: a struct
/// containing itself by value has no size in C, so no permutation
/// compiles and `cc` reports the cycle either way. The point of the
/// `visiting` arm is termination, not ordering.
pub fn emitStructsInDependencyOrder(self: *Generator, module: *const ast.Module) EmitError!void {
    var state: std.StringHashMapUnmanaged(StructEmitState) = .empty;
    for (module.items) |item| {
        if (item.kind == .struct_def) {
            try state.put(self.arena, item.kind.struct_def.name, .unvisited);
        }
    }
    for (module.items) |item| {
        if (item.kind != .struct_def) continue;
        try self.emitStructAfterDeps(module, item.kind.struct_def, &state);
    }
}

pub fn emitStructAfterDeps(
    self: *Generator,
    module: *const ast.Module,
    s: ast.StructDef,
    state: *std.StringHashMapUnmanaged(StructEmitState),
) EmitError!void {
    switch (state.get(s.name) orelse .unvisited) {
        .emitted, .visiting => return, // already done, or a cycle: see the doc comment
        .unvisited => {},
    }
    try state.put(self.arena, s.name, .visiting);
    for (s.fields) |f| try self.emitDepsOfType(module, &f.ty, state);
    try state.put(self.arena, s.name, .emitted);
    try self.emitStruct(s);
}

pub fn emitDepsOfType(
    self: *Generator,
    module: *const ast.Module,
    ty: *const ast.TypeExpr,
    state: *std.StringHashMapUnmanaged(StructEmitState),
) EmitError!void {
    switch (ty.*) {
        .name => |n| {
            if (state.get(n) == null) return; // a builtin or an enum, not a struct in this module
            for (module.items) |item| {
                if (item.kind != .struct_def) continue;
                if (!std.mem.eql(u8, item.kind.struct_def.name, n)) continue;
                try self.emitStructAfterDeps(module, item.kind.struct_def, state);
                return;
            }
        },
        .optional => |inner| try self.emitDepsOfType(module, inner, state),
        .list => |inner| try self.emitDepsOfType(module, inner, state),
        .ref => |r| try self.emitDepsOfType(module, r.inner, state),
        .result => |r| {
            try self.emitDepsOfType(module, r.ok, state);
            try self.emitDepsOfType(module, r.err, state);
        },
        .unit => {},
    }
}

/// `CELL_DEFINE_OPTIONAL` lines for every optional the module names that
/// cell_rt.h does not already instantiate. They come after the struct
/// typedefs because an optional over a struct needs that struct first.
pub fn emitOptionalInstances(self: *Generator) EmitError!void {
    var seen: std.ArrayList(OptionalInst) = .empty;
    for (self.module.items) |item| {
        switch (item.kind) {
            .fn_def => |f| {
                for (f.params) |p| try self.collectOptionals(&p.ty, &seen);
                if (f.return_type) |rt| try self.collectOptionals(&rt, &seen);
                if (f.body) |body| try self.collectOptionalsInStmts(body, &seen);
            },
            .struct_def => |s| for (s.fields) |fld| try self.collectOptionals(&fld.ty, &seen),
            else => {},
        }
    }
    if (seen.items.len == 0) return;
    for (seen.items) |inst| {
        try self.writer.print("CELL_DEFINE_OPTIONAL({s}, {s})\n", .{ inst.base, inst.elem });
    }
    try self.writer.writeAll("\n");
}

pub fn collectOptionals(self: *Generator, ty: *const ast.TypeExpr, seen: *std.ArrayList(OptionalInst)) Alloc!void {
    switch (ty.*) {
        .optional => |inner| {
            const inst = try self.optionalInstance(inner);
            if (inst.generated) {
                for (seen.items) |existing| {
                    if (std.mem.eql(u8, existing.base, inst.base)) break;
                } else try seen.append(self.arena, inst);
            }
            try self.collectOptionals(inner, seen);
        },
        .list => |inner| try self.collectOptionals(inner, seen),
        .ref => |r| try self.collectOptionals(r.inner, seen),
        .result => |r| {
            try self.collectOptionals(r.ok, seen);
            try self.collectOptionals(r.err, seen);
        },
        .name, .unit => {},
    }
}

pub fn collectOptionalsInStmts(self: *Generator, stmts: []const ast.Stmt, seen: *std.ArrayList(OptionalInst)) Alloc!void {
    for (stmts) |s| {
        switch (s.kind) {
            .let => |l| if (l.ty) |t| try self.collectOptionals(&t, seen),
            else => {},
        }
    }
}

/// A C `main` that calls the Cell `main`, so a module with an entry point
/// links into an executable. Without this there is no path from `.cell` to
/// a program.
pub fn emitEntryPoint(self: *Generator) EmitError!void {
    const def = self.findFn("main") orelse return;
    if (def.body == null) return;
    if (def.params.len != 0) return;

    const out = self.writer;
    try out.writeAll("// C entry point for the Cell `main`.\n");
    try out.writeAll("int main(void) {\n");
    const ret = if (def.return_type) |rt| try self.lowerType(&rt, .owned) else CType.void_type;
    if (ret.shape == .integer) {
        try out.writeAll("  return (int)cell_main();\n");
    } else {
        try out.writeAll("  cell_main();\n  return 0;\n");
    }
    try out.writeAll("}\n");
}

// ── items ───────────────────────────────────────────────────────────

pub fn emitStruct(self: *Generator, s: ast.StructDef) EmitError!void {
    const out = self.writer;
    try out.print("typedef struct cell_{s} {{\n", .{s.name});
    for (s.fields) |f| {
        const ty = try self.lowerType(&f.ty, f.ownership);
        try out.writeAll("  ");
        try self.writeDecl(ty, f.name);
        try out.print("; // {s}\n", .{@tagName(f.ownership)});
    }
    try out.print("}} cell_{s};\n\n", .{s.name});
}

/// A payload-free Cell enum is a distinct integer type of width int32_t
/// (cell_rt.h section 6). A bare `typedef enum` has implementation defined
/// width, so the typedef is explicit and the constants live in an
/// anonymous enum. They are enum constants rather than `static const`
/// because an unused `static const` trips -Wunused-const-variable in C.
pub fn emitEnum(self: *Generator, e: ast.EnumDef) EmitError!void {
    const out = self.writer;
    try out.print("typedef int32_t cell_{s};\n", .{e.name});
    if (e.variants.len == 0) {
        try out.writeAll("\n");
        return;
    }
    try out.writeAll("enum {\n");
    for (e.variants, 0..) |v, i| {
        try out.print("  cell_{s}_{s} = {d},\n", .{ e.name, v, i });
    }
    try out.writeAll("};\n\n");
}

pub fn emitPrototype(self: *Generator, f: ast.FnDef) EmitError!void {
    if (f.is_public) try self.writer.writeAll("// export\n");
    try self.writeSignature(f);
    try self.writer.writeAll(";\n");
}

/// The C symbol a function definition or declaration carries. Mangling is
/// `cell_<name>`, except that a BODYLESS declaration of a runtime
/// intrinsic takes the runtime's own spelling: a declaration means "this
/// symbol comes from elsewhere at link time", and `assert(cond, msg)`
/// lives there as `cell_assert_msg`. A function with a body is never
/// renamed, because that would define over a runtime symbol.
pub fn symbolFor(self: *Generator, f: ast.FnDef) Alloc![]const u8 {
    if (f.body == null) {
        if (intrinsicSymbol(f.name, f.params.len)) |sym| return sym;
    }
    return try std.fmt.allocPrint(self.arena, "cell_{s}", .{f.name});
}

pub fn emitFn(self: *Generator, f: ast.FnDef) EmitError!void {
    const body = f.body orelse return;
    const out = self.writer;

    self.locals.clearRetainingCapacity();
    self.current_fn = f.name;
    self.current_ret_ty = if (f.return_type) |rt| try self.lowerType(&rt, .owned) else CType.void_type;
    for (f.params) |p| {
        // An `owned` or `arc` parameter is the callee's to release
        // (runtime/cell_rt.h section 7), so it enters the drop pass like
        // a `let`; `pendingDropsSince` still filters on its ownership and
        // on `wasMoved`. R11 row 1, closed 2026-09-16.
        try self.pushLocal(p.name, try self.lowerType(&p.ty, p.ownership), p.ownership, true);
    }

    try self.writeSignature(f);
    try out.writeAll(" {\n");

    // -Wunused-parameter is part of -Wextra, and a Cell body is free to
    // ignore a parameter, so name the unused ones explicitly.
    for (f.params) |p| {
        if (stmtsUse(body, p.name)) continue;
        try out.print("  (void){s};\n", .{p.name});
    }

    // Not `self.emitStmts(body, 1)`: that helper pops every local it
    // sees back off `self.locals` in its own `defer` before returning,
    // which would erase the function's own top-level `let`s before
    // `emitScopeDrops` ever got to look at them. Inlined here so the
    // drop pass runs while they are still visible; `self.locals` is
    // cleared in full below regardless, so no scope actually leaks.
    self.current_after = blockExit(body);
    for (body, 0..) |_, i| {
        try self.emitStmt(&body[i], body[i + 1 ..], 1);
    }
    if (!endsInReturn(body)) try self.emitScopeDrops(1, blockExit(body));
    try out.writeAll("}\n\n");
    self.locals.clearRetainingCapacity();
}

pub fn writeSignature(self: *Generator, f: ast.FnDef) EmitError!void {
    const out = self.writer;
    const ret = if (f.return_type) |rt| try self.lowerType(&rt, .owned) else CType.void_type;
    const symbol = try self.symbolFor(f);
    if (ret.pointer) {
        try out.print("{s}{s}(", .{ ret.text, symbol });
    } else {
        try out.print("{s} {s}(", .{ ret.text, symbol });
    }
    if (f.params.len == 0) {
        // C11: an empty list is an unprototyped declaration, not a
        // zero-argument one.
        try out.writeAll("void)");
        return;
    }
    for (f.params, 0..) |p, i| {
        if (i > 0) try out.writeAll(", ");
        try self.writeDecl(try self.lowerType(&p.ty, p.ownership), p.name);
    }
    try out.writeAll(")");
}

pub fn writeDecl(self: *Generator, ty: CType, name: []const u8) EmitError!void {
    if (ty.pointer) {
        try self.writer.print("{s}{s}", .{ ty.text, name });
    } else {
        try self.writer.print("{s} {s}", .{ ty.text, name });
    }
}
